### ISSUE TITLE
Improve Auto Hide functionality

### ISSUE THREAD

**Issue by fofajardo** [FranklinDM/TGS#27]
## Main Point
AiOS issue: AddonLab/AiOS#18

>Could you add a switch for auto-hide?
>
>  - [x]  Auto show & auto hide
>  - [x]  Auto show, not auto hide
>  - ~~Auto show. If later user click mouse within the side bar area, do not auto hide. Otherwise (if the side bar is never focused), auto hide.~~
>
>This is the feature I'm really missing..... (Yeah... a very great feature in an old but really good browser Sleipnir 2)

## Second Point
- [x] Allow the sidebar switch to be completely invisible while retaining its function (like [Sidebar Auto Show/Hide](https://addons.mozilla.org/en-US/firefox/addon/sidebar-auto-showhide/) does)
- [x] Automatically hide real sidebar switch when this feature is enabled
- [x] Resolve remaining conflicts (*)

## Others
- [x] Convert '__hide sidebar if the mouse cursor is:__' option to a dropdown menu and make it available by default (not hidden in advanced mode)

**Comment by FranklinDM** [comment]
- [ ] Modify autohide function
- [ ] Create prefs for this
- [ ] Add to options window
- [ ] Update locales 
- [ ] Test if it works properly

**Comment by sergeevabc** [comment]
Dear @FranklinDM, could you be so kind to make white border (which is shown when panel is hidden) optional? Currently I have to use [Sidebar Auto Show/Hide][1] extension which has no such visual annoyance.

[1]: https://addons.mozilla.org/en-US/firefox/addon/sidebar-auto-showhide/

**Comment by PeterTriac** [comment]
@FranklinDM Thanks! for TGS; I am leaving the sinking FF-ESR ship now it becomes a Trabant-browser...
When my mouse touch the left-edge of the screen, the sidebar appears.
I would like the sidebar NOT to disappear afterwards when the mouse does other things.
So the sidebar has to stay visible while doing other browsing-things.
Than.. my mouse touch the left-edge of the screen again and the sidebar has to disappear again.
I think this is an later-version option..? (or I am blind ? ;-) (I use AiOS for 10+ years).. "it saved my live"  ;-)
Sorry if other people above are meaning the same issue..
Englisch is not my native language..
(Latest Pale Moon, Win. 10 64b).

**Comment by fofajardo** [comment]
@PeterTriac Noted, this is already in the list of tasks for part 1.
@sergeevabc Added to Part2 of the task list.

**Comment by fofajardo** [comment]
@PeterTriac sorry if I kind of misunderstood, but this is actually already available in the current version (1.0.4) as of the time of writing:

You need to enable advanced mode first via the bottom-left settings button:
![capture2](https://user-images.githubusercontent.com/11641537/32481381-0c56881c-c3ce-11e7-837c-d8c74a0b13f3.PNG)

Then under the `General` tab, click the Sidebar Switch tab and under `Appearance`... 
![capture3](https://user-images.githubusercontent.com/11641537/32481420-31210b54-c3ce-11e7-8ffc-47ebd2dcd986.PNG)

Select the `is held on sidebar switch option`
![capture](https://user-images.githubusercontent.com/11641537/32481331-e3cc4b52-c3cd-11e7-8735-0b69f3299526.PNG)

**Comment by PeterTriac** [comment]
Thanks , for your anser   !!
I am blind ;-)
I overlooked the "Advanced Mode"
I hope, Pale Moon will work for ever.. ;-)  (Will be difficult..)

There has to be an "old fasion adjustable browser" with FF<57 "old extentions".
Maybe Mozilla can make some money with Firefox ESR 52 . 5 , 6 , 7 , 8 , 9 , 10 , 11 ,12 , 13 , 14 , 15 ,16 , 17 , ... ;-)
I go to bed for now ( 04:16 ...

**Comment by sergeevabc** [comment]
@FranklinDM, did you get a chance to look into ```Part 2```?

**Comment by fofajardo** [comment]
@sergeevabc Yes, I did. The initial commit for the feature is already completed (locally, cant find time to update the GitHub repo) and will try to fix a small conflict with the auto hide feature. When this is all finished, v1.0.5 will be released.

**Comment by sergeevabc** [comment]
Thank you, sir.

**Comment by sergeevabc** [comment]
Thank you, sir.

---

I click “Toggle sidebar automatically” to keep sidebar opened, but it adds unnecessary border when the invisible switch is used.

Also it would be convenient to have “Options…” in “[gear_icon] Tools…”  or somewhere else in the sidebar, don’t you think?

Delay works unexpectedly. I set it to 1000 ms to avoid showing sidebar when cursor briefly touches the screen border, nonetheless the sidebar is displayed, just 1 second after.

**Comment by sergeevabc** [comment]
Delay works unexpectedly. I set it to 1000 ms to avoid showing sidebar when cursor briefly touches the screen border, nonetheless the sidebar is displayed, just 1 second after.

**Comment by fofajardo** [comment]
@sergeevabc Can you test and try installing this one? (You need to remove the .zip from the end of the file name)
[TGS-v105-1a.xpi.zip](https://github.com/FranklinDM/TGS/files/1545340/TGS-v105-1a.xpi.zip)

There is already an Options menu item in the sidebar, via the panel list:
![capture](https://user-images.githubusercontent.com/11641537/33802455-b1175630-ddb2-11e7-8552-a8b9cea92e17.PNG)

**Comment by sergeevabc** [comment]
Delay works as expected now, however I am surprised you use the same value to show and to hide the sidebar. The former is meant to avoid brief touches on a trigger area, hence hundreds+ ms, but the latter is hardly desirable by everyone, hence a way to set it to 0 ms is expected. For example, I open a link from bookmarks, then I put the cursor away to hide the sidebar, yet have to wait until the delay ends.

As for lack of Options menu item and unnecessary border, I invite you to watch this GIF to grasp the crux:

![](http://images.vfl.ru/ii/1512902890/3faf9b23/19755948.gif)

**Comment by fofajardo** [comment]
There is a menu item for the options in the panel menu by default. Please check if you have these 2 boxes checked in the Options window (can be launched by Ctrl+Shift+F4), under the Menus category.
![capture](https://user-images.githubusercontent.com/11641537/33804443-19e725aa-dde0-11e7-9fd6-62c69d533eea.PNG)
Which should appear like this:
![capture4](https://user-images.githubusercontent.com/11641537/33804454-5a3a75f8-dde0-11e7-80ca-1c4cef1f7f4d.PNG)

The unnecessary border (or the sidebar switch) doesn't appear if auto-hide is enabled (u can permanently hide that by setting its width to 0 in the advanced settings) and the reason why options won't be placed in the Tools menu because it is already available via the menu above ^ (if you have it checked) and it is for a specific panel's functions (Bookmarks, History, MultiPanel) only.

A separate delay for hide + show may be considered in the next release (probably 1.0.6), I'll inform here if I do.

**Comment by sergeevabc** [comment]
>  Please check if you have these 2 boxes checked in the Options window under the Menus category

OK, works now.

> The unnecessary border (or the sidebar switch) doesn't appear if auto-hide is enabled

GIF was recorded with auto-hide enabled and invisible switch enabled,
but even so the border becomes visible when “Toggle sidebar automatically” is clicked.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by FranklinDM** [comment]
Hi,

Sorry for the quite late reply. This is already done in my local repository.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by fofajardo** [comment]
@sergeevabc Can you try the latest release, v1.0.6?

**Comment by sergeevabc** [comment]
I see the progress now, yet it’s still buggy.
For example, press F11 to switch to full screen, then press again, then… sidebar no longer responds.

**Comment by fofajardo** [comment]
The fullscreen issue is separate from this one — it doesn't save the previous state properly (remove the SB switch) and deserves its own issue.

**Comment by sergeevabc** [comment]
Also, it’s not convenient that you _hardcoded mouse clicks_ to control the sidebar. For example, I use _middle click_ to open a bookmark in a background tab and sometimes accidentally miss, but then _the superfluous toolbar_ is shown. Let alone _large tooltips_, especially one which pops up when I touch the screen border.

![](https://pli.io/W82jU.png)
---
![](https://pli.io/W1iRq.png)
---
![](https://pli.io/W1oEG.png)

How to disable all that stuff?

**Comment by sergeevabc** [comment]
Another bug. Hide toolbar inside sidebar, close sidebar, then right click somewhere next to addressbar and invoke Customize window, close it, then open sidebar… its toolbar has become visible for no reason.

**Comment by fofajardo** [comment]
@sergeevabc Sorry for the late reply.
- The big tooltip for the sidebar switch can be disabled by setting `extensions.aios.switchtip` to `false`. (#30)
- The toolbar & sidebar appearing when Customize mode is enabled is intentional as it avoids another bug (a workaround). I think I can add code that restores the previous state when exiting customize mode.
- I'll try to add an option to disable/configure clicks on the invisible sidebar switch.
