### ISSUE TITLE
Add Basilisk as a target application

### ISSUE THREAD

**Issue by fofajardo** [FranklinDM/TGS#35]
A separate branch for this would be ideal as we need to apply some commits that would make present day Pale Moon break.

We actually support this already from our initial fork point but I removed it because it is not necessary for PM users (and Basilisk is still TBA at that time).

This is going to take some work (well, really) because we need to...
- [x] Support the inferior _'CustomizableUI'_
- [x] Fix duplicate extension pref naming (extensions.aios.extensions.aios)
- [x] Fix style for Back/Forward/Reload/Stop buttons (#55, point 6, fixed in 178204e)
- [x] Fix PageInfo (Opening Page Info inside a tab will NOT be fixed unless someone would propose a solution)
- [x] Optimize add-ons page layout (fixed in e3bada14845bdad38e16cb470919c3b05888d95d)

Work for this could be found here: https://github.com/FranklinDM/TGS/tree/development

**Comment by FranklinDM** [comment]
This is going to take some work (well, really) because we need to...
- [x] support the inferior 'CustomizableUI'
- [ ] Fix MultiPanel styling for address bar
- [ ] Fix PageInfo (broken by async changes)
- [ ] Optimize add-ons page layout

**Comment by fofajardo** [comment]
In case anyone wants a test build (this is based on an older version of TGS, however):
[tgs_sidebar-basilisk-dev-build-pm.xpi.zip](https://github.com/FranklinDM/TGS/files/1998201/tgs_sidebar-basilisk-dev-build-pm.xpi.zip)
You need to remove the (.zip) extension in the file name in order to install this.
