### ISSUE TITLE
Getting back the old Downloads "pop-up" thing instead of Library

### ISSUE THREAD

**Issue by Rising-Soul** [FranklinDM/TGS#40]
I disabled "Open downloads in sidebar", because I keep my bookmarks/Scrapbook X open most of the time and don't want downloads taking over the sidebar.

But now when I click the Downloads button, it opens my downloads in the Library window, instead of the pop-up it used to open.

How can I get that back?

**Comment by fofajardo** [comment]
TGS currently defaults to showing the Downloads window and it is currently not possible to instead open the Downloads popup.

An option to open the Downloads popup instead of the window will be implemented in the next version (1.0.6)

**Comment by FranklinDM** [comment]
TGS currently defaults to showing the Downloads window and it is currently not possible to instead open the Downloads popup.

An option to open the Downloads popup will be implemented in the next version (1.0.6)

**Comment by Rising-Soul** [comment]
Thank you! :)
