### ISSUE TITLE
Do not open sidebar on new windows

### ISSUE THREAD

**Issue by vinipsmaker** [FranklinDM/TGS#71]
Would it be possible to make it optional to open sidebar alongside news windows? Having the sidebar automatically open on every new window annoys me.

**Comment by fofajardo** [comment]
@vinipsmaker Sorry for the years-late response, but yes, you can configure this in TGS Options:
<img width="406" alt="Screenshot 2023-01-29 194354" src="https://user-images.githubusercontent.com/11641537/215323936-2a193f58-ac18-44a4-8bec-32dc0769e1df.png">
Just go to `The Good 'ol Sidebar Options > General > Behavior` and under `Browser Startup`, set both **Sidebar** and **Toolbar** options to **Close Sidebar** and **Hide Toolbar** respectively.

**Comment by vinipsmaker** [comment]
thank you, @FranklinDM
